language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  - EVM_EMACS=emacs-25.1
  - EVM_EMACS=emacs-25.2
  - EVM_EMACS=emacs-25.3
  - EVM_EMACS=emacs-26-pretest
  - EVM_EMACS=emacs-git-snapshot

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot

before_install:
  - source .travis-paths.sh
  - ./.travis-before-install.sh
  - evm install $EVM_EMACS --use --skip
  - make emake.el

script:
  - make build/libegit2.so
  - make test
