language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx

cache:
- directories:
  - "$HOME/emacs"

env:
  global:
    - EMACSCONFFLAGS="--with-x-toolkit=no --without-x --without-all --with-xml2 --with-modules --with-toolkit-scroll-bars=yes --with-gameuser=$USER"
    - PATH="$HOME/bin:$PATH"
  matrix:
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=snapshot

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot

before_install:
  - make emacs
  - make emake.el

script:
  - make build/libegit2.so
  - make test
